:PROPERTIES:
:ID:       f02e96d6-a4e1-4b93-a31a-29f32dd13a1f
:END:
#+title: Thoughts 9/20/21
#+date: [2021-09-20 Mon 14:28]


Some things I was thinking about:

How the way computers work is a good framework through which to view
the human psychology.

everyone evaluates if statements and conditionals within their minds as
they go about their lives.

Some peoples logic processors are not as good as other peoples

The recusive aspects, how life is just a big recursion, that is what
the spiral is all about. Everything comes back around

---
The idea that you get to know how to program by looking at other
programs and refactoring them into your own programs.

there is a bunch of stuff on git hub that would be good for this.

I also need to get my own repository setup and upload the various
java programs that I have made so far.

---
all the xscreensaver programs are open source and online at github.
But they are written in c, and so you will be learning c.

I should try to implement the same type of thing in windows, using java
if I can. I'm sure there is something similar.

I would like to try and find some lisp programs that are already made
and learn more from refactoring them.

---
One of the biggest things is figuring out what parts that I need to
implement to do whatever.

The sky is the limit I just have to decide what I want to do. 


----
----
A computer uses routines to perform tasks. It has been prepared to recieve
a specific type of input inorder for it to know exactly what to do.
You must have a dialog with the computer.
You tell it something and then it returns something else.
If it is not what you anticipated or if the computer throws an error
and fails to understand what you said you must change what you say.

Understanding what to say and how to say it, it what order. These are
very important considerations. There are diffrent languages that people
have developed to communicate with a computer.
There are several things that make a language either good or bad.
Some languages are better for certain taks than others.
Sometimes you need really stable code. Sometimes you just
need to make a simple relation. Quickly connect two things..

I believe that for me, what a computer could be is like wood to
a carpenter. the ability to make the tools and jigs that you need
to make other more beautiful things.

Thats what i look forward to doing with a computer. Here is this abstract
thing which allows you to create pretty much anything that you can imagine
within the normal bounds. But really, any type of process, any form of
abstraction that you can imagine, can be created. Many useful tools
no doubt have already been created. 
