:PROPERTIES:
:ID:       d3146f27-bac4-4a06-913f-1838c5d7c511
:END:
#+title: React Development
#+date: [2021-09-04 Sat 23:04]

This is where information on React will go.

* Node.j Stuff
** Link to [[id:a52745dc-0f03-46a8-a233-9a51bc5e1ab1][Node.js]]

** Went setting up a new react app I had to start powershell with special arguments
   
   
** To start and stop react server
   to stop hit C-c
   to start run npm start in the app folder



* Other elements to learn with react

* BootStrap.css
  Here is a website that details bootstrap.css
  [[https://getbootstrap.com/docs/3.4/css/][website link]]

* React Tutorial 1

The tutorial that I am currently watching is
[[https://www.youtube.com/watch?v=Ke90Tje7VS0][video link]]

It teaches and shows you how to make a mobile application

when you build a user interface with React you are
building a bunch of independent, isolated and reuseable components.

The component is a central idea in react.js development.

Each application has at least one component. This is the root componenet.
This root componenet also contains all the other child components.

Every react applicaiton is built in this tree hierarchy.

Example code of a component:

#+begin_src java script
  
  class Tweet {
      state = {};
  
      render() {
      }
  }
  
#+end_src


* Setup

  The Tutorial is using create-react-app version 1.5.2, current version is 4.0.3

** To run react we need to have Node.js installed
   Then run this command in the terminal

   npm i -g create-react-app@1.5.2

** then you run $: create-react-app <app name>
   If this is the first time running this it is going to install react
   as well as other third party packages like
   
*** A light-weight development server
    
*** Webpack - for bundling our files
    
*** Babel - for compiling our java script code
    
*** Then we will cd to the app dir and type $: npm start

*** they also want you to have visual studio code

   And they have you install extensions in VS code.

**** Simple React Snippets by Burke Holland

**** Prettier code formatter

    Enable formatting on save within VS Code


* Begin Creating your first app

** First you create a new project
  
*** run $: create-react-app <name of project>

*** then cd to the folder of your project
    and type $: npm start
    
** create a file filename.jsx
   the extension jsx is used to give you more code completion options
  This file is created within the Compoenets directory inside the
  src folder.

** the first thing you must do is import React

#+begin_src java script
  
  import React, { Component } from 'react';
  
  class | Counter extends Component {
      state = {}
	render() {
  
  
      }
  }
  
  export default Counter;
  
#+end_src
   
   That is the first iteration:
   The last line can be combined with the class initialization:
   Some things can be simplified to get this result:

   
#+begin_src java script
  
  import React, { Component } from 'react';
  
  export default class | Counter extends Component {
	  render() {
	  return <h1>Hello World</h1>;
      }
  }
  
#+end_src

