:PROPERTIES:
:ID:       a9472e8b-b363-47d0-997c-490d1f3f1f8b
:END:
#+title: Thoughts 12/26/21
#+date: [2021-12-26 Sun 22:37]


Even free money still comes with a cost.

Free money comes with a cost.

Christ's sacrifice says so many things.
If used as a template for spirituality it is very effective.

And its because it describes the spiritual behavior of lots of
different things.

Christ dying on the cross tells me that everything, every action in the
universe comes at a cost. The creator of the universe in following the
laws of said universe, gave his son as payment so that we might live life
more abundantly. Through him we take part in what will continue on eternally.
Our Eternal Life. Being apart of the movement of the universe. A movement
that you hope is not towards destruciton.

What is destruciton but a wish for the present moment to remain. It is a
selfish cry from the current age, we will not fall to the next iteration.
Because sometimes people don't realize they are a part of everything. You
are just a small piece of the universe. People either can't wrap their minds
around this, or choose to see themselves separate from everything else.
That is what causes selfish behavior. If you know that you are just an
arm. Its ok let another arm take my place. Hopefully I can encourage
the next arm to work even better than I did. 

Every action in the universe come at a cost.
This is because each moment is spent in becoming
and so if the moment is not spent in making or moulding yourself then it
is for not. Every moment works to change use and mould us weather we choose
it to or not. Therefore the cost is revealed in every moment. You only have
so much energy to spend, that is a fact.
Now the amount that is accomplished seems a little subjective. Because
sometimes you gain a little over a long time and other times you gain
a lot over a short amount of time. But experience is incremental and pretty
steady. Put yourself in a situation repeatedly and your mind will adapt to
that situation.

And the reason that some situation are better than others is due to the
part of the mind that they are developing.

Learning to play a musical instrument.
This process that the brin goes through to learn and adapt to the musical
instrument, may cause the development of more foundational mental processes
that then cause a higher intellect all around. Or at least in some areas.

This is possibly the way that the mind becomes unbalanced. Too much time
spent in one enviroment. One type of thinking. One perspective. One house.
