:PROPERTIES:
:ID:       889948be-40b1-489a-a3f0-fed26982e3e0
:END:
#+title: Thoughts 10/28/21
#+date: [2021-10-28 Thu 19:11]


Learning is all about repetition over time.

If your mind is repeatedly exposed to something. Then after
a while it naturally gets ingrained within the mind and
easy to recall and relate to other things.



11/3/21

I am thinking about how to make a template of the central index
buffer. I thought about making a table with the words for the
various topics in it, and putting it at the top of each tramplate
so then you can make a new heading and put it in a category too.

I made the mega-emacs with the screen divided into three sections
in one window. Its nice.

The [[id:5ecfd482-a98f-4eab-b842-f6b00428090b][Program journal]] is a very important piece of writing. There
is much opportunity in studying it.

I wanted to set up a thing where everyday at a certain time I would
just write down what I was thinking about at that time. It would
be a cool study. And it would give me more a sense of obligation
to a behavior, or routine. See what it is like to disrupt your
routine a little.

<2021-11-08 Mon 23:38>

I had a great time at the DEvICT meeting tonight. I got there early
and met this guy Roger as he was leaving. He let me in because there
weren't any of the other guys there yet. We talked about being a
self taught programmer. I feel like these guys don't try hard enough.
Everyone is wanting to use a pre-made framework to do this or that.
Why not take the time to learn how to do it yourself? Everyone is
in such a hurry to get somewhere that they dont realize it but they
arrive with only half the stuff they had before. Ya you made it, but
you are missing all these things. What ever happened to just allowing
things to take as long as they should take to happen? We as humans must
intervene in everything. If it is too slow we speed it up, if it is too
fast we slow it down.

Overall I am so thankful, so thankful that something like this exists for
me to go to. I am learning so much, I am making friends, I am helping others
too. With so much going on it is even more important to try to stay focused.
Once you have a good grasp of things.... there's just so much out there.
Once you have a good grasp of things you can pull from so much stuff and
remake it into what you want. You can look at the source of web-pages and
see how they did this or that. I am just beginning but I feel like I have
already traveled far. I feel like I am making good progress. That's good
because things are happening much faster now-a-days. The world itself is
changing at an alarming rate. I wish to understand computers and thereby
prepare myself for the outcome of this changing world. No matter what
it becomes, computers will be at the heart of it. Teach someone to
program a computer and they will be able to do anything. Frequently I
need things that have never existed before. This will give me the ability
to create them. 





