<<<<<<< HEAD
:PROPERTIES:
:ID:       d3146f27-bac4-4a06-913f-1838c5d7c511
:END:
#+title: React Development
#+date: [2021-09-04 Sat 23:04]

This is where information on React will go.

* Node.j Stuff
** Link to [[id:a52745dc-0f03-46a8-a233-9a51bc5e1ab1][Node.js]]

** Went setting up a new react app I had to start powershell with special arguments
   
   
** To start and stop react server
   to stop hit C-c
   to start run npm start in the app folder



* Other elements to learn with react

* BootStrap.css
  Here is a website that details bootstrap.css
  [[https://getbootstrap.com/docs/3.4/css/][website link]]

* React Tutorial 1

The tutorial that I am currently watching is
[[https://www.youtube.com/watch?v=Ke90Tje7VS0][video link]]

It teaches and shows you how to make a mobile application

when you build a user interface with React you are
building a bunch of independent, isolated and reuseable components.

The component is a central idea in react.js development.

Each application has at least one component. This is the root componenet.
This root componenet also contains all the other child components.

Every react applicaiton is built in this tree hierarchy.

Example code of a component:

#+begin_src java script
  
  class Tweet {
      state = {};
  
      render() {
      }
  }
  
#+end_src


* Setup

  The Tutorial is using create-react-app version 1.5.2, current version is 4.0.3

** To run react we need to have Node.js installed
   Then run this command in the terminal

   npm i -g create-react-app@1.5.2

** then you run $: create-react-app <app name>
   If this is the first time running this it is going to install react
   as well as other third party packages like
   
*** A light-weight development server
    
*** Webpack - for bundling our files
    
*** Babel - for compiling our java script code
    
*** Then we will cd to the app dir and type $: npm start

*** they also want you to have visual studio code

   And they have you install extensions in VS code.

**** Simple React Snippets by Burke Holland

**** Prettier code formatter

    Enable formatting on save within VS Code


* Begin Creating your first app

** First you create a new project
  
*** run $: create-react-app <name of project>

*** then cd to the folder of your project
    and type $: npm start
    
** create a file filename.jsx
   the extension jsx is used to give you more code completion options
  This file is created within the Compoenets directory inside the
  src folder.

** the first thing you must do is import React

#+begin_src java script
  
  import React, { Component } from 'react';
  
  class | Counter extends Component {
      state = {}
	render() {
  
  
      }
  }
  
  export default Counter;
  
#+end_src
   
   That is the first iteration:
   The last line can be combined with the class initialization:
   Some things can be simplified to get this result:

   
#+begin_src java script
  
  import React, { Component } from 'react';
  
  export default class | Counter extends Component {
	  render() {
	  return <h1>Hello World</h1>;
      }
  }
  
#+end_src

=======

:PROPERTIES:
:ID:       d3146f27-bac4-4a06-913f-1838c5d7c511
:END:
#+title: React Development
#+date: [2021-09-04 Sat 23:04]

This is where information on React will go.

* VScode hints

  to get everything looking good you need to reset the tabs.
  you can do this by typing shift-alt-f

  

* React Dojo Tutorial

** Purpose of the directories and files

*** the node_modules folder
    This is where our project dependencies are stored
    including the react library itself and any other libraries
    that we may install later.
    
**** This folder is large in size
     This folder contains the whole react library and is very large
     and so if you download a project from github its most likely
     not going to contain this folder so in this case, to install
     the folder into the project, if you are in the project folder
     then you run

     npm install

     This will look in the package.json file and install the dependencies
     necessary for the current project.

     then to run the project again you can type

     npm run start

     to reload the project.

*** The public folder
    This is where the public files (public to the browser)
    This is where the index.html file is, this file is what will
    display the app. It is where react sends all the information to.
    Within the index.html is the <div> with the class ROOT, which is
    referenced in the Javascript

*** the SRC folder
    This is where all of the coding we will be doing is. When we create
    react components they will exist in this folder. The main file is
    the index.js file. That is what kickstarts our app.

    NOTE: <React.StrictMode>
    that means that react does additional checks and gives us warnings
    down in the console.
    
    
**** For this tutorial there were some files that we deleted
     
***** test file, apptest.js

***** reportWebVitals.js this a performance file
      and then we removed the import for it in index.js

***** setuptests.js another test file

      
*** Package File
**** package.json
     this file includes links to the dependencies of our project
     it also includes scripts that we can use to start the server
     build the app for production or test the app or eject the webpack
     file.
     
*** 

* Online Courses

  [[https://www.youtube.com/watch?v=w7ejDZ8SWv8][React JS Crash Course 2021]]

  [[https://www.youtube.com/watch?v=4UZrsTqkcW4][Full React Course 2020 - learn Fundamentals]]

  [[https://www.youtube.com/watch?v=j942wKiXFu8&list=PL4cUxeGkcC9gZD-Tvwfod2gaISzfRiP9d][Full Modern React Playlist]]

* javaScript Ideas to know

** Variables

** If/Else Conditionals and Switch Statements

** Differeces between var, let, and const

** Functions

** Arrays

** Array Methods like filter, map, and reduce

** ES6 Concepts

** Promices

** Callbacks

** Async/await

** Classes and OOP Concepts

** Working with API's

* What You need to know in React

** JSX

** Components (Functional and Class based)

** Lifecycle Methods

** State

** Props

** Handling Events

** Forms

** Conditional Rendering 

** Working with third-party APIs

* Node.j Stuff
** Link to [[id:a52745dc-0f03-46a8-a233-9a51bc5e1ab1][Node.js]]

** Went setting up a new react app I had to start powershell with special arguments
   
   
** To start and stop react server
   to stop hit C-c
   to start run npm start in the app folder



* Other elements to learn with react

* BootStrap.css
  Here is a website that details bootstrap.css
  [[https://getbootstrap.com/docs/3.4/css/][website link]]

* React Tutorial 1

The tutorial that I am currently watching is
[[https://www.youtube.com/watch?v=Ke90Tje7VS0][video link]]

It teaches and shows you how to make a mobile application

when you build a user interface with React you are
building a bunch of independent, isolated and reuseable components.

The component is a central idea in react.js development.

Each application has at least one component. This is the root componenet.
This root componenet also contains all the other child components.

Every react applicaiton is built in this tree hierarchy.

Example code of a component:

#+begin_src java script
  
  class Tweet {
      state = {};
  
      render() {
      }
  }
  
#+end_src


* Setup

  The Tutorial is using create-react-app version 1.5.2, current version is 4.0.3

** To run react we need to have Node.js installed
   Then run this command in the terminal

   npm i -g create-react-app@1.5.2

** then you run $: create-react-app <app name>
   If this is the first time running this it is going to install react
   as well as other third party packages like
   
*** A light-weight development server
    
*** Webpack - for bundling our files
    
*** Babel - for compiling our java script code
    
*** Then we will cd to the app dir and type $: npm start

*** they also want you to have visual studio code

   And they have you install extensions in VS code.

**** Simple React Snippets by Burke Holland

**** Prettier code formatter

    Enable formatting on save within VS Code


* Begin Creating your first app

** First you create a new project
  
*** run $: create-react-app <name of project>

*** then cd to the folder of your project
    and type $: npm start
    
** create a file filename.jsx
   the extension jsx is used to give you more code completion options
  This file is created within the Compoenets directory inside the
  src folder.

** the first thing you must do is import React

#+begin_src java script
  
  import React, { Component } from 'react';
  
  class | Counter extends Component {
      state = {}
	render() {
  
  
      }
  }
  
  export default Counter;
  
#+end_src
   
   That is the first iteration:
   The last line can be combined with the class initialization:
   Some things can be simplified to get this result:

   
#+begin_src java script
  
  import React, { Component } from 'react';
  
  export default class | Counter extends Component {
	  render() {
	  return <h1>Hello World</h1>;
      }
  }
  
#+end_src

>>>>>>> 2189245692e7e52370ca8345e7e7628bc3a123c2
