:PROPERTIES:
:ID:       a7263498-ab00-4cdb-86c3-dc8c9404aec6
:END:
#+title: Thoughts 9/3/21
#+date: [2021-09-03 Fri 12:59]

I'm trying to think of what I was going to type.

So often I wish for something else, but then I realize that my life
is exactly how I want it to be. And if I was anywhere else I would
just wish I was back here. But the mind longs for somehting else
constantly. Its part of those things that we must learn to control.
There are good and bad voices within our minds and too often it is
the negative influence that is heard over the positive influence.
We have to work to disregard that which we shouldn't do and work to
seek out that which we should do. I guess that is the univereses
tendency towards chaos and entropy. Organization, dicipline always
comes with a challenge.

Sacrificing is a way of overcomming these things. The best answer always
is to do without. It has become a way within my mind of getting back
at those voices that I wish to ignore. I just don't do anything.
If there is a desire that arizes within me then I purposefully dont
fulfill it. Its like if you are asking the question of should you
do it, then the answer is no. If it is not a necessity, then you don't
need it.

People don't realize the joy and satisfaction that comes with
doing without. You are satisfied because you were able to overcome
that thing which many people succumb to. And that in itself differentiates
me from everyone else. And that makes me feel good. I don't want to
be like everyone else. I want to walk the path less traveled. It is
the more beautiful, more peaceful way to go. Because people are
disgusting.

---
In my mind I can slowly see these things taking shape. I try to imagine
what it might be like in a year or so when I have developed these
tools more and there is a wealth of information to pull from.

I was thinking how convenient it would be to add commentary to my
journal entries if one was in one buffer and the commentary page
was in another. But that would require typing out each journal
page, or finding a way to display images in emacs. Typed text
would be better however. I could format and adapt the text as I
went along. 



