:PROPERTIES:
:ID:       31a74b33-d492-4098-b33a-7e2e6caa99b1
:END:
#+title: Thoughts 10/2/21
#+date: [2021-10-02 Sat 21:41]

The point is
the important thing is
to develop your process of adaptation instead of
trying to prevent some one thing from happening.
If you spend all this time trying to prevent something from happening
and in the end something else equally as devestating happens and
you are unable to recover, unable to adapt.

Ona small scale. In our everyday lives. Lets try to adapt as much as possible
to the environment. Instead of forcing the environment to bow to our will.
Specifically pertaining to individual psychology.

now if the same idea is implemented on a societal level, the effects can be
devastating to both the individual and the environment.

The process of adaptation, the process of evolution is what should be studied
How do you increase the rate of evolution? How can you learn more and go farther?
What happens if you advance faster than your environment?
What happens if you overrun your resources?

there must be three things...

there is the individual
there is the environment
there is the collective consciousness that pervades spirit and matter

text only is a world all of its own. It is separate from normal consciousness.
Communities can thrive in text based environments because it takes a certin type
of mindset to find yourself wishing to participate in such a thing.

There is a drag on social interaction for some reason. It just doesnt sound
very appealing. This is a fault in the way I currently view the world Im sure
but that is just the way it is. The shape of ourselves changes and morphs into
that which it presently is. Just as we are, it is. Does a child look like an
adult? there are similarities, but much has changed. the overall form stays the
same. Says recognizable, distinguishable from other permanent objects.

But a face is not just a face, it is also, the attitude, and the energy behind it,
that makes a face what it is, or who it is. 

---
think of a pixel as a paint brush

Like if you were to display something like the evolution sequence, how it takes
up a window of emacs. Write an emacs program that uses characters. random characters
fill a specified area and then there is a function that defines two different states
of the characters either on or off. Then you define those states, off is off but on
can mean that the charachter is bright and then the characters around it slowly
taper-off in brightness, so that you can create a figure by turning on and off
certain charaters.

then animate the drawings...

----
Be innovative god damnit!
Do something different.
Now of all times is the time to do somthing different
our world is changing drastically with new forms of destruction
and new forms of prosperity.
With the internet, you have access to all of these different ideas
and personalities.

Such a diverse sample you see before you. the presence of so mant things.

As much as I was capable of, I was in love with him. -norma
