:PROPERTIES:
:ID:       3236ea92-2542-448a-9311-a793a1fe32ed
:END:
#+title: Thoughts 11/29/21
#+date: [2021-11-29 Mon 11:40]

* The End of The Human Era
AI has already begun. You cannot stop our inevitable future. We
will eventually have to seccumb the the AI.

The day will come when we will cease to be human beings as we know
them today. We will become something different, but we will retain
similar aspects.

This knowledge that what you are creating will eventually kill you.
This is not something to be scared of, with this realization we
join the multitudes before us. Congratulations, you've just become
a member of the club. So many things live only to be eventually
consumed. Join the club and stop holding on to something that is
disolving before your eyes. Change is the only constant in the universe.

Why do you think that you are special? Why do you wish to distinguish
yourself from the rest of the universe? What power do you have
alienated, all alone in the universe? Why not realize that you are
the universe and everything is connected and made up of the same
particles, the same matter. But you are so arrogant and self-centered,
you think you are something special, that you are not like all the other
things in the universe. That you came from something else...

You are just ignorant and stubborn. But time will show you the truth.
There are no lies that can stant the test of time. All will be revealed.
That which has no foundation, deteriorates quickly in the light of the sun.

---
* Parallels Between The Individual and Society.
So, society and the individual run parallel to each other. You wish to
understand society, observe and study the behaviors of the individual.
Then you will be able to create categories , classifications, and types.
And then you can apply these to an understanding of the whole of society.

Because there exists this type of behavior in the individual then that
behavior is also performed by the society as a whole, to some extent.
Some behaviors will be more prominent than others.

----
* People Discriminating against language
There are so many words. Everyone should be allowed to choose which words
they wish to use. And have a style all their own. If people have trouble
understanding them, let them inquire, and let them then offer to reveal
themselves.

---
* Text Recognition Software
The shape, its the shape of the word that counts. How many words have
exactly the same shape? If you take the context into consideration then
you should be able to arrive at an understanding. (Text Recognition)

It won't be perfect, but if it can get 80% of it, then that will be
good. You'll just have to proof read it. 

---
* What causes bad behavior?
  
So there is this behavior that people do where if they don't get their
way or someone doesn't want to do what they want them to do then, they
explode, they shout, they thow things they yell and maybe even get
physically violent with anyone who is in their vicinity.

Maybe they do this behavior because they don't know what else to do?
They don't know how to achive what they want without the cooperation
of other people, they don't know how to make it work, without
hurting someone, or manipulating someone. The point is, this is
their behavior because they don't know how to do anything different.
Maybe they have been told what they should do but, that behavior is
a lot harder to do than , the behavior that they perpetuate.

They also have a hard time thinking through problems, this maybe is
the origin of the problem. That is the main goal here is to try to
figure out what is the root cause of this behavior. I have seen it
perpetrated by many different people, but it is perpetrated
differently in each person it seems. One peron will have problems
dealing with other people and yet when confronted by a physical
problem, they are able to troubleshoot it and think through it to
get a solution. But when it comes to dealing with people they are
comfounded, they cannot imagine a solution to the problem besides
having an explosion and leaving the situation. Of course dealing
with people is very different than dealing with physical objects.
People have a tendency to make arriving at a solution pretty difficult.
With physical objects you know that if you do this then its likely
that you will get this result. Not so much with people. One
behavior may produce a solution in one situation but make things
worse in another.

So here we have arrived at another realization. The solutions for
the physical world can be established and then cataloged and
reused several times. But when youare dealing with people you are
almost forced to start from scratch each time and develop a
solution that is completely tailored to the situation and person
at hand. And so when dealing with people you must have a lot
of patience and be willing to start over, from the beginning.

This may be the main trait that these people lack, the ability or desire
to start over, to forfeit all the established knowledge and experience
and begin again, seeing everything in a new light.

I see it as a challenge. I know that the only thing that is keeping this
person from what they wish to achieve is their own mind. The first step
is to get them to differentiate between themselves and their mind. Before
you do this they will feel like they are battling themselves. And you can't
make very much progress this way. They need to see that their mind has a
mind of its own, and we as individuals must learn to understand our minds,
so that we can wield it as the incredible tool that it is. Like hauling a
huge claymore into battle, if you are not trained it the use of your weapon
then it will do nothing more than cause you to be destroyed. It crushes
you under its own weight. You think that you are free, but you're not,
you are a slave to your own mind. You are at the mercy of its whims.

You cannot do much in the way of internal advancement until you come
to the realization that you and your mind are two different things.
You must also realize that how you define youself, because this
will be the determining factor between whether you enable yourself
to change or prevent yourself from changing. 

That movie 'I Heart Huccabys' was eye opening for me. It was
more of a reassurance that I was on the right track. But it really
helped to show the value of getting rid of your definitions.
Letting go of those ideas that you were brought up with and
really taking the time to define the world in your own unique way.

* Why is it so frustrating to drive?

First of all everyone is in this competitive race. But the competition is
not just about how fast we can drive, its also about how loud your
vehicle is, and how large your vehicle is, and how much you can just not
give a shit about anyone but yourself.

This is how I feel when I have to drive around these people. And you must
drive very defensively cause people will box you in and put you in
compromising situations. It's almost as if they are trying to get you
to be in an accident. They are trying to make you wreck your car.

