:PROPERTIES:
:ID:       4ec49c50-1806-40d3-98ff-2528b837048f
:END:
#+title: Thoughts 9/9/21
#+date: [2021-09-09 Thu 08:31]

As soon as I put my computer away, that is when I get the idea
that i need to write down. So I must get my computer out
again .

In life you need to just snuggle up to suffering and pain.
Make them your best buddies.
Because the more that you suffer the more you are able to
endure, and the earier life in general is.
Because life is suffering. And its all about how much suffereing
you are able to endure.
If you are familiar with suffereing and you have had to endure it
many times before, when you are presented with it,
when you find yourself in a situation where you are forced to suffer
then its no big deal to you, you are like ok whatever, I can do this
and if it will make other people feel better, or if it will solve
the problem, or if it will accomplish the task then I will do it.

That is one of the reasons why I have never become addicted to anything
it is because I am a friend of suffering.
When I begin to crave something I just tell myself that it no longer exists
And then there is nothing I can do to satisfy my desire so I will just
suffer without, and eventually the desire will go away, be gone.

Desire is something that doesnt last forever. It vanishes pretty quickly
especially if you convince yourself that there is no way that that
desire can be fulfilled.

I walk to my car and I am ready to leave for work, but then I remember that
I have forgotten somthing. This is frustrating because now I must get
back out of my car and go and unlock my door and get the thing that I forgot
all of this seems like wasted energy, because if I would have just
remembered everything that I was supposed to remember then I would
not be doing this right now, I would not be held back from accomplishing
my goal of getting to work. But now since I have forgotten, I must do
more work, I must incur a setback and redo the work that I have already done.

this is a form of suffering that people frequently put themselves through.
And it causes some people to become very angry, espectially when they think
back at all the other times that this has happened to them. They become more
and more streesed out, the become more and more frustrated and then they
inevitably take it out on someone around them, or they act rude to people
and they are mad at other people because they are mad at themselves.

We would have a completly different experience with this if we changed our
perspective and looked at the whole situation differently. When we realized
that we forgotten something, if we jsut accept it and go and get the thing
that we forgot, knowing that we were adding more suffering to our lives but
then in acceptance of that we are ok with it and we agree that it is not
the end of the world and that we will be ok. We should just relax and
do now what is necessary for us to do. We realize that soon, very soon, we
will have gotten what we forgot and be back in our car and headed to work.

This is just ourselves,  it is we who are adding this suffering to our lives.
Imagine if it was someone else that was adding the suffering to our lives.
In many cases this would make us even more upset and frustrated. Because
now its not our own fault that we are suffereing it is someone elses fault.
Literally something that is beyond our control is causing us to suffer.
Not entirely beyond our control because we feel we can yell and degrade
this person and then maybe they will stop causing us to suffer. Or we
could even stop having relationships with this person and then maybe
our lives would have less suffering but is that really the case? Would
that actually happen?., maybe to an extent but you cannot eliminate suffering
from your life. It will always be there in some extent. Whether it is
something that you create or something that is created by a person or
entitiy outside of yourself. It will always be there. So why not embrace
it, cuddle up to it, be friends with it, even welcome it at times.

Suffering has an added bonus that many people fail to realize as well.
This is the fact that when you suffer and you have been suffering for
a while and then finnaly the suffering is released, you feel a wave of
joy that pours over you. You feel true emotional bliss. Its like taking
a drug that gives you a euphoric feeling. But in the case of taking a
drug you get the euphoric feeling up front and then you inevitably have
the crash afterwards. When you work and you struggle and suffer and then
the suffereing is lifted, or the work is done, and you are headed home,
there is no side effect to worry about. You began by sacrificing and
now you feel joy , you get that wonderful euphoric feeling, you've
already paid the price and now you are reaping the benefits. In the
case of taking drugs you are stealing that feeling, you get the feeling
and youdidnt have to do anything to achieve it or obtrain it, beside
taking the drugs, and therefore you are in debt and will inevitably
have to pay the price for your actions because evetually everything
seeks a balance in the end, everything equals out and the debts are
repaid. You are going to feel bad when you are forced to repay your
debt and this causes you to want the drugs again to re-live that good
feeling. What people don't realize is that they are borrowing this feeling.
It isn't there's, they are obtaining it unnaturally and eventually
they will have to pay the price for it. Because their behavior is unnatural
it is also unsustainable and will only last a limited amount of time.

