:PROPERTIES:
:ID:       36ee9c2d-06ee-4281-b9cd-e28a60d462c7
:END:
#+title: Thoughts 1/1/22
#+date: [2022-01-01 Sat 16:16]


Think about before television and before microphones and
recording. The position that a musical performer had in society
was very different then.

Its new years day.
Last night was a rollercoaster of fun chaos. I was up until 4am.
I was over at Tim house and just like normal, every holiday tends
to get a lil crazy. I couldnt stop laughing, I took my violin over
there. That was the first time that I had played my violin in a while.
It went pretty good. The violin seems to be much easier to play then the
viola just because its smaller.

Its 4:24pm now and Im still not quite back to normal.
It's 9 degrees outside. There was ice and a lil bit of snow last night.
I had to help bruce put up these storm windows, my hands were about
to fall off. So cold.

Norma is becoming harder to deal with. Bruce is under a lot of stress
right now. I try to do what I can to watch norma. But it is still
very hard on him.


1/2/22


Im trying to determine what I want.
I was thinking about how I wished i could be back in that time period
of my life where I didnt have to worry so much about what was going to
happen. Right now there seem to be many things that at any moment could
come crashing down. The biggest thing right now is Bruces sanity and
his ability to take care of his mother. There is also the fact of the
tenants and how at any moment something could go wrong with any of the
tenants. My job seems to be pretty stable right now, however I am working
on training myself to get a better job. I feel like I need more money to
ensure everything will be ok in the future. I also need health insurance.

I want to not have to worry about what is going on with bruce and his mom.
But that's what happens when you start helping other people out, their
problems become your problems.

I feel like I have just enough energy to be ok, but I'm teetering on the
edge, and its scary. This is just how I feel in my mind. The buffer is
shrinking. But all is not lost yet, i still have all of my utilities and
resources. I can stiall do everything that I set out to do. My life used
to be more relaxed, now its kinda stresful. It seems like I am waiting
for something. 


